### ISSUE TITLE
Subfolder not being added

### ISSUE THREAD

**Issue by RaymondTMartin** [lhjamieson/COSC401MajorProject201920#10]
Steps taken to achieve this error:

1. Click on up arrow to upload file
2. Click browse
3. Select mp4 file
4. Click on the mp4 file
5. Click on add subfolder
6. Click away
7. Subfolder disappear  

Note: Probably occurs with other file types

**Comment by zlokquay** [comment]
This is likely because you can't actually create a subfolder of a non-folder type. If we introduce a check before the button operated, we can avoid this behavior.

**Comment by zlokquay** [comment]
This is likely because you can't actually create a subfolder of a non-folder type. If we introduce a check before the button operated, we can avoid this behavior.

**Comment by rickrome** [comment]
Fix is ready to test under IssueFixes branch.

**Comment by TWalkerSMCM** [comment]
This is also an issue with the actual react-file-browser library we downgraded the version and it went away. Make sure to run an npm install if it still exists.

**Comment by MattHeitmann** [comment]
This issue has been fixed
