### ISSUE TITLE
Doesn't allow me to register with Mac.

### ISSUE THREAD

**Issue by JakeH123197** [lhjamieson/COSC401MajorProject201920#20]
![Image 3-3-20 at 11 26 AM](https://user-images.githubusercontent.com/44817303/75796555-d968c180-5d41-11ea-900b-89147bea2272.jpeg)

**Comment by TWalkerSMCM** [comment]
The way we store users is prohibitive for running the solution on a Mac. For now, it doesn't make sense to switch the database as the server this is going on runs Windows.

**Comment by MattHeitmann** [comment]
I am going to close this issue because once we deploy the server this won't be a problem.
